name: Rust
on:
  push:
    branches: ["main"]
    paths-ignore: ["book/**"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Free up disc space
      run: sudo rm -rf /usr/share/dotnet /opt/ghc "/usr/local/share/boost" "$AGENT_TOOLSDIRECTORY"
    - name: Setup toolchains
      run: rustup install nightly
    - name: Build
      run: cargo build
#    - name: Nightly test
#      run: cargo +nightly rustc -- -Z macro-backtrace
    - name: All feature tests
      run: cargo test --workspace --all-features
    - name: Build without features
      run: cargo test --workspace --no-default-features
    - name: Build without features
      run: cargo test --workspace --no-default-features --features derive
